import Head from 'next/head';
import Image from 'next/image';
import styles from '../ui/styles/Home.module.css';

export default function Home() {
    return (
        <div>
            <Head>
                <title>TreinaBlog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
}
